### ISSUE TITLE
It's unclear how to set tenant_id and client_id

### ISSUE THREAD

**Issue by colobas** [dask/dask-adlfs#1]
Trying to use this for the first time. Running the following:
```
>>> import dask_adlfs
>>> import dask.dataframe as dd
>>> df = dd.read_csv("adl://somedatalakestore.azuredatalakestore.net/somefile.csv")
```

Yields:
```
File "<stdin>", line 1, in <module>
File "/usr/local/lib/python2.7/dist-packages/dask/dataframe/io/csv.py", line 391, in read
    **kwargs)
File "/usr/local/lib/python2.7/dist-packages/dask/dataframe/io/csv.py", line 271, in read_pandas
    **(storage_options or {}))
File "/usr/local/lib/python2.7/dist-packages/dask/bytes/core.py", line 138, in read_bytes
    None, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/dask/bytes/core.py", line 394, in get_fs_paths_myopen
    encoding=encoding, errors=errors, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/dask/bytes/core.py", line 260, in __init__
    self.fs = _filesystems[self.protocol](**self.storage_options)
File "/usr/local/lib/python2.7/dist-packages/dask_adlfs/core.py", line 32, in __init__
    self.do_connect()
File "/usr/local/lib/python2.7/dist-packages/dask_adlfs/core.py", line 37, in do_connect
    client_secret=self.client_secret)
File "/usr/local/lib/python2.7/dist-packages/azure/datalake/store/lib.py", line 110, in auth
    raise ValueError("tenant_id and client_id must be supplied for authentication")
ValueError: tenant_id and client_id must be supplied for authentication
```

These are assigned a default value of `None` here: https://github.com/dask/dask-adlfs/blob/5d8333ca8cd81571c271901b549a86df66c11230/dask_adlfs/core.py#L23-L27

**Comment by colobas** [comment]
Ok I understood now that you have to pass the `storage_options` dict like so:
```
df = dd.read_csv("adl://somedatalakestore.azuredatalakestore.net/somefile.csv",
                            storage_options={"tenant_id" : "something", "client_id" : "something"})
```

**Comment by mrocklin** [comment]
Is there a nicer way to authenticate with Azure that would remove he need
for adding authentication information?

**Comment by martindurant** [comment]
@mrocklin , I am not aware of a way to get Azure default credentials, but I would be surprised if there isn't one, probably in https://github.com/AzureAD/azure-activedirectory-library-for-python. I would ask some people at MS directly.

**Comment by mrocklin** [comment]
> @mrocklin , I am not aware of a way to get Azure default credentials, but I would be surprised if there isn't one, probably in https://github.com/AzureAD/azure-activedirectory-library-for-python. I would ask some people at MS directly.

@noelbundick or @zooba might know the right people to contact about helping out here

**Comment by zooba** [comment]
@lmazuel may be able to help, but I suspect the easiest way is to use classes from [msrestazure](https://github.com/Azure/msrestazure-for-python) (which should already be installed as a dependency of the DataLake SDK)

**Comment by colobas** [comment]
What about a similar thing for azure blob storage? I reckon it resembles S3 better and is much cheaper. And the authentication is done via shared secrets rather than active directory credentials.

**Comment by martindurant** [comment]
@colobas , it's simply a case of no-one having spent the time to look into it. I don't know how usable the existing MS library code might be for deriving from.

**Comment by zooba** [comment]
@colobas The library you want in that case is [azure-storage](https://github.com/Azure/azure-storage-python), and it should be pretty trivial to map. It is essentially the same thing as S3, though with some bonus features essentially layered on top of blob storage.

Both would be good though, as DataLake is the better service for "dump all my files and process them later" (though it comes with its own analytics service, but *I'd* rather use Dask, so I guess other people would too :) )

**Comment by lmazuel** [comment]
Thanks @zooba for the mention :)
There is two ways to automatically authenticate a ServicePrincipal for the SDK, without any configuration:
- [Use the currently loaded Azure CLI 2.0 profile](https://docs.microsoft.com/en-us/python/azure/python-sdk-azure-authenticate?view=azure-python#mgmt-auth-cli)
- [Using an authentication file and set it to env variable AZURE_AUTH_LOCATION](https://docs.microsoft.com/en-us/python/azure/python-sdk-azure-authenticate?view=azure-python#mgmt-auth-file)

This will require this dask module to depends on `azure-common`, and a few code in this dask file (i.e. if CLI, try CLI, ifnot, try env variable, if not, die, etc.). And probably a few changes for me as well, since these are tight to SDK client, I'm sure there a small gap to fill to make them a little more generic. But that makes sense to enable this scenario :)

**Comment by colobas** [comment]
@martindurant @zooba thanks for the replies!

@martindurant not complaining that it doesn't exist yet, just trying to gather the info needed to maybe kickstart it myself :)

@zooba you mean the library I want if I'm thinking to implement this type of dask connector?

**Comment by zooba** [comment]
@colobas That's right. Our Azure library is broken up more than boto, so sometimes it's less obvious that you don't need to depend upon the whole thing. (In particular, `azure-mgmt-*` will pull in a lot of dependencies, and if you're just trying to use one of the client libraries then you'll want to bypass that by depending on the more specific piece.)

Our Azure SDK expert is @lmazuel, so feel free to call him in whenever you have questions :)

**Comment by colobas** [comment]
@zooba thanks a lot for the quick answers and tips! Take care and have a good holiday

**Comment by martindurant** [comment]
@lmazuel , assuming you do 
```
from azure.common.client_factory import get_client_from_cli_profile
from azure.mgmt.compute import ComputeManagementClient

client = get_client_from_cli_profile(ComputeManagementClient)
```
how do you get the appropriate credentials out of the client object?

**Comment by lmazuel** [comment]
@martindurant It's why I was saying "And probably a few changes for me as well, since these are tight to SDK client" :)
But you can do
```python
import azure.common.credentials
credentials, subscription_id = get_azure_cli_credentials()
```
From the credentials attributes, you should be able to get client_id (not tested).
